### ISSUE TITLE
Tagging Capital Framework releases

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#108]
We eventually want to start tagging and [releasing](https://github.com/cfpb/capital-framework/releases) pre-compiled CF zips. At CFPB we subscribe to the [semver](http://semver.org/) spec but in the grand scheme of CF, how will we decide what constitutes a major/minor/patch update?

For example, let's say CF is tagged 0.4.5. If we update cf-buttons and it goes from 0.2.3 to 0.3.0, would we re-compile all of CF and bump it to 0.5.0, uploading a new zip? Or would the cf-buttons change only push CF to 0.4.6? Or maybe we leave it at 0.4.5 if the change is insignificant.

It's going to be a headache if every update to a component warrants a new CF release. Should we just play it by ear and only bump CF when we feel something "significant" has changed?

**Comment by himedlooff** [comment]
Seems like we're ok with https://github.com/cfpb/capital-framework/issues/108#issuecomment-61333258 as a guide.

In order to do this we will need to pin the Capital Framework deps that are used to create the zip file. These ones: https://github.com/cfpb/capital-framework/blob/gh-pages/build/bower.json#L16-L24

When we create a new on-demand zip we would manually bump those deps. The numbers we bump there will determine the tagging the repo.
