### ISSUE TITLE
This is too meta

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#176]
I'm not a fan of the fact that the `gh-pages` branch of this repo is housing both the docs site and the master capital-framework component itself.

You get weirdness like:

- [it depending on itself](https://github.com/cfpb/capital-framework/blob/gh-pages/bower.json#L18)
- an unhelpful description in the Bower registry:

  ![screen shot 2015-06-05 at 12 39 21](https://cloud.githubusercontent.com/assets/1044670/8010718/7444e710-0b80-11e5-9a38-f95e7bb742fa.png)
- and the README being all about the site, not the master component.

Perhaps we should move the component stuff to the (currently non-existent) `master` and build the docs site separately in `gh-pages`?

**Comment by contolini** [comment]
Would this mean we'd change the default branch of this repo to `master`? Any ramifications of that?

BTW, good to have you back, @Scotchester. :smiley:

**Comment by Scotchester** [comment]
Yes I think we would. I don't foresee any major ramifications.

Good to be back :) Though I've got to go back into my non-CF-projects hole for the rest of the day.

**Comment by contolini** [comment]
Also: This repo should not list itself as a dep. That's a bug that needs to be fixed ASAP.

**Comment by ascott1** [comment]
I'm way late to this game, but this is very off to me too. I never had considered that this would be used as a dependency and the fact that it's published to Bower at all seems like an accident/holdover from when this repo housed a component.

When this repo is being used as a dependency,  it's primarily for the CFPB specific theme which is also housed in the generator. My suggestion is that we split that off into it's own repo, so that it's not maintained in two places.

This repo does house the "compiled" version of CF, which is difficult to keep up to date. I'm all ears if anyone has a suggestion for how to handle that better.

I'm tagging @cfarm, because she brought this to my attention.

Thoughts @Scotchester @contolini @cfarm?

**Comment by himedlooff** [comment]
I wonder if we set up the repo more like [Bootstrap's](https://github.com/twbs/bootstrap) where they have the docs in a sub directory on master and push only docs to gh-pages. 

https://gist.github.com/cobyism/4730490
`git subtree push --prefix docs origin gh-pages`

**Comment by KimberlyMunoz** [comment]
>This repo does house the "compiled" version of CF, which is difficult to keep up to date. I'm all ears if anyone has a suggestion for how to handle that better.

[Greenkeeper.io](http://greenkeeper.io/) can be used to do automatic PRs when things get out of date.

Although I've just been re-thinking the benefits of having all these modular repos versus one clearly maintained Capital Framework repo with the modules broken up into multiple, modular, clearly labeled LESS/JS files that can be commented out. That's probably throwing out the baby with the bathwater. 🛁

**Comment by Scotchester** [comment]
Closed with the completion of Voltrazord.
