### ISSUE TITLE
[cf-core] Add note about comments within .respond-to mixins

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#204]
Originally from https://github.com/cfpb/cf-core/issues/15

TIL that you cannot use traditional CSS `/* ... */` comments inside the statement block of our `.respond-to` mixins. Less will not compile, giving the following error:

```sh
>> ParseError: unmatched `/*`
```
Additionally, you cannot comment out **a single, unmatched curly brace** inside the `.respond-to` statement block. Less will get to the end of the document and think that there is an unmatched curly brace missing its partner.

These quirks should be documented alongside the `.respond-to` mixins.

**Comment by Scotchester** [comment]
Discovered more info about this today.

The problem seems to be be related to our previous method of concatenating all CF less files before compilation. Here's what I encountered:

- Working on a legacy project, fin-ed-resources, I replaced the previous version of cf-layout with the most recent version of it.
- Received the error described.
- Removed the entirety of the updated component from the concatted `capital-framework.less` file; error went away.
- Put it back. Noticed some comments within some `.respond-to` mixins in the updated component. However, _none of them used the_  `/* … */` _syntax_.
- Removed the latest-appearing comment within a mixin; error goes away again.
- Turns out, it was a two-line comment, both lines beginning with `//`. Noticed that higher up, there were one-line comments within a respond mixin, which did not cause the Less compilation error.
- Tried removing just one line of the two-line comment, and the error went away again.

Moral of the story? Within a `.respond-to` You can use **neither** `/* … */` comments **nor** multiline `//` comments.

_Unless_, it would seem, you're using the new standard Capital Framework workflow, which doesn't seem to have a problem with this. I used it on [tax-time-saving](https://github.com/cfpb/tax-time-saving/blob/master/src/static/css/main.less#L11), which just imports each component into the `main.less` file with no concatenation, and it works fine. :confounded: 

So I'm not really sure if this really needs to be documented anymore, as we're moving toward the new concat-less workflow. Gonna go ahead and close this issue. Feel free to reopen if you think it warrants more discussion.
