### ISSUE TITLE
[cf-typography] Make .date mixin?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#232]
Reported by @anselmbradford in https://github.com/cfpb/cf-typography/issues/37

The [`.date` class](https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L231-L235) seems a little inflexible. Some areas may want to use a date and designate it with a `.date` class, but not have it be `h5()`. Would it make sense to make this a mixin instead? Implementing projects could do:

```
.date {
    .date();
}
```

If they want the whole site to follow the generic date styles, or:

```
.example-page {
    .date {
        .date();
    }
}
```

If they wanted to only apply the date format to a page on the site.

As it is now if a page wanted to override the date styles, a new date class either needs to be created or each style needs to be overridden. Any thoughts on this?

**Comment by KimberlyMunoz** [comment]
Hey Ans, a little background on this. Why wouldn't we be able to create a .date__small or .date__big class? I'm wondering if the mixin approach is really atomic.

**Comment by KimberlyMunoz** [comment]
@anselmbradford

**Comment by anselmbradford** [comment]
@KimberlyMunoz Yeah, I think you're right. The original issue was that dates were used in several different contexts, some of which didn't make sense to have an h5 size setting. One suggestion I'd have with that approach is if possible to lean toward modifiers that describe the context of where the date is used instead of the appearance, so like instead of `date__big` it might be `date__heading` for a date that appears in an h1 or whatever.

**Comment by KimberlyMunoz** [comment]
Thanks, I'm going to close this issue. I'm sure .date__big and .date__heading will happen as the need arises.
