### ISSUE TITLE
Support large text labels

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#545]
## Current behavior

- The labels of checkboxes are created with `a-label` and assume a rather short label, however, there are instances where the label is multiple paragraphs of text with a link, which makes the behavior of checking the label to check the box less desirable. 

## Expected behavior

- This is up for discussion. Is there an invisible label for 408 compliance or an aria-label attribute? And the text is not clickable for clicking the label.

## Steps to replicate behavior

1. Visit step three of the complaint intake form (consumerfinance.gov/complaint)
2. See the checkbox after the text input that has two paragraphs and a link.

## Screenshots

__Current__

![screen shot 2017-07-21 at 6 17 04 pm](https://user-images.githubusercontent.com/704760/28484519-e2f971ce-6e40-11e7-8dd7-285386292896.png)

**Comment by jimmynotjim** [comment]
That seems like an improper label. Instead of making all that text the label, it should probably be a description after the label, similar to what we do on the OaH feedback form (though I'm pretty sure we're not supposed to use italics like that page does) 

https://www.consumerfinance.gov/owning-a-home/help-us-improve/

**Comment by anselmbradford** [comment]
The problem I ran into is that the checkbox is created by applying styles to a label. So remove the label; remove the checkbox.

**Comment by jimmynotjim** [comment]
You'd still have a label, just not one with so much text. I imagine it could be broken up like 

---------

__By checking this box, I want the CFPB to publish this description on consumerfinance.gov blah blah blah.....__
- [ ] I permit the CFPB to publish my response

**Comment by anselmbradford** [comment]
Ahhhh I see what you're thinking!

cc'ing @kurzn as that would be a UX decision.

**Comment by ielerol** [comment]
This one isn't my project, but I would definitely support splitting this so the checkbox label itself is short, with a separate paragraph of explanation text, over trying to make a code solution that works for labels this long.

I expect there needs to be some stakeholder review of the specific language used, since it looks like the current label will need a decent amount of rewriting to make sense as two separate chunks.

**Comment by kurzn** [comment]
I see where you're coming from with this. Unfortunately, this label cannot be rewritten easaily. I tried to make it more user friendly during the project and there was legal pushback. It's a sensitive issue that would require full clearance if we want to open back up. 

There would also be concern that users wouldn't read the separate explanation text, which I could see stakeholders having a problem with. 

Is there no technical solution to this?

**Comment by jimmynotjim** [comment]
I'm sure there is, but I still have huge concerns with this design. Another issue I hadn't even considered is, typically the label text is connected to the checkbox, so you can make the target large enough for improved usability. When you place a link in the label, you're now doubling up on that interaction, because clicking the link also checks the box. This forces users to check and then uncheck the box just to learn what it is they are checking. Improving the usability and breaking up the text really seems like the appropriate action here, even if the stakeholder doesn't exactly like it.

**Comment by jimmynotjim** [comment]
@anselmbradford this was fixed right?

**Comment by anselmbradford** [comment]
> @anselmbradford this was fixed right?

Eh it was "fixed" with JavaScript.

**Comment by jimmynotjim** [comment]
I mixed up what problem this issue was addressing. Breaking the default browser behavior, especially in light of our browser support work, is something we should not be doing within the framework. If anyone feels strongly otherwise, lets discuss it in the next browser support meeting. For now I'm closing with "won't fix".
