### ISSUE TITLE
Fix capital-framework package

### ISSUE THREAD

**Issue by cfarm** [cfpb/capital-framework#708]
Fix `capital-framework` package so it successfully installs in projects and all the component styles work as expected.

## Current behavior

- `npm install`-ing `capital-framework` into a project such as `cfgov-refresh` (instead of individual components) results in Less compilation errors. component's Less stylesheets are not found by the `gulp-less` plugin which means gulp build won't work.

## Expected behavior

- installing `capital-framework` package instead of individual packages does not cause `gulp build` to fail on Less compilation step.

## Steps to replicate behavior

1. in `cfgov-refresh` project, replace all `cf-` prefixed components in `package.json` with just the capital-framework component: `"capital-framework": "latest"`,
1. run `./frontend.sh` or `gulp build`

## Screenshots

__Current__
![screen shot 2017-12-08 at 1 43 49 pm](https://user-images.githubusercontent.com/702526/33780283-3c35ef74-dc1e-11e7-961f-5b6609310935.png)

![screen shot 2017-12-08 at 1 43 56 pm](https://user-images.githubusercontent.com/702526/33780282-3c1b169a-dc1e-11e7-806d-465523a0ab34.png)

__Expected__

**Comment by contolini** [comment]
I've always liked the idea of being able to `npm install capital-framework` but it hasn't gotten much adoption so it's not very well tested. 😔 

The solution here might be to modify [these lines](https://github.com/cfpb/cfgov-refresh/blob/master/gulp/config.js#L64-L68) so that gulp searches the correct directories for the files? I *think* this is an issue with the gulp configuration of projects consuming CF and not CF's structure itself. Not 100% sure but that's what my gut says.

**Comment by anselmbradford** [comment]
I'm unable to replicate this. Perhaps it was fixed with the move to lerna? Can we update the testing instructions or close? (cc @cfarm)

**Comment by cfarm** [comment]
If you followed the steps here and it worked then that sounds great to me!
