### ISSUE TITLE
Incorrect styling for button links

### ISSUE THREAD

**Issue by dcmouyard** [cfpb/capital-framework#794]
The text color for button links doesn’t match the text color for links, it currently uses the visited link color.

## Current behavior

- `<button class="a-btn a-btn__link">` has a text and border color of teal #257675
- `<a>` has a text and border color of pacific #0072ce

## Expected behavior

- `<button class="a-btn a-btn__link">` has a text and border color of pacific #0072ce

## Steps to replicate behavior

1. Create a button with the `a-btn__link` class.

## Screenshots

__Current__
![screen shot 2018-04-16 at 3 13 37 pm](https://user-images.githubusercontent.com/135259/38830087-2b2d6150-4189-11e8-83de-ee1615465582.png)

__Expected__
![screen shot 2018-04-16 at 3 16 34 pm](https://user-images.githubusercontent.com/135259/38830093-31013de0-4189-11e8-9fc5-c9f710cabeb4.png)

**Comment by Scotchester** [comment]
Bug :(

It's been fixed in... wait for it... [the same update that added support for SVG icons](https://github.com/cfpb/capital-framework/commit/dbc2fe30b158b7d7a8f5813e1134272ee50f628b#diff-4655c69cbb96f7538e91637c9e573f3dR18).

We continue to inch closer to figuring out our testing situation on that PR, but for now I'd recommend that you make a quick fix in your project Less that you remove when you remove the temporary icon code.
